# Generated by Django 2.2 on 2020-04-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_poll_app', '0004_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
